# Generated by Django 5.1.4 on 2024-12-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
