# Generated by Django 5.1.4 on 2024-12-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
